[package]
name = "hive-cell-wasm"
description = "The tier 0 hivebox driver, running WebAssembly cells on wasmtime."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true
readme.workspace = true
publish.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
bytes.workspace = true
futures.workspace = true
hive-cell.workspace = true
hive-drone.workspace = true
hive-proto.workspace = true
hive-types.workspace = true
rustix = { workspace = true, features = ["time"] }
tokio = { workspace = true, features = ["fs", "macros", "net", "rt", "sync", "time"] }
wasmtime = { workspace = true, features = ["async", "cranelift", "parallel-compilation", "pooling-allocator", "runtime", "std"] }
wasmtime-wasi = { workspace = true, features = ["preview1"] }

[target.'cfg(target_os = "linux")'.dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
wasmtime = { workspace = true, features = ["wat"] }

[lints]
workspace = true
