# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from hivebox.v1 import cells_pb2 as hivebox_dot_v1_dot_cells__pb2
from hivebox.v1 import types_pb2 as hivebox_dot_v1_dot_types__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in hivebox/v1/cells_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CellsStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_stream(
                '/hivebox.v1.Cells/Create',
                request_serializer=hivebox_dot_v1_dot_cells__pb2.CreateRequest.SerializeToString,
                response_deserializer=hivebox_dot_v1_dot_cells__pb2.CreateEvent.FromString,
                _registered_method=True)
        self.Get = channel.unary_unary(
                '/hivebox.v1.Cells/Get',
                request_serializer=hivebox_dot_v1_dot_cells__pb2.GetCellRequest.SerializeToString,
                response_deserializer=hivebox_dot_v1_dot_types__pb2.Cell.FromString,
                _registered_method=True)
        self.List = channel.unary_unary(
                '/hivebox.v1.Cells/List',
                request_serializer=hivebox_dot_v1_dot_cells__pb2.ListCellsRequest.SerializeToString,
                response_deserializer=hivebox_dot_v1_dot_cells__pb2.ListCellsResponse.FromString,
                _registered_method=True)
        self.Watch = channel.unary_stream(
                '/hivebox.v1.Cells/Watch',
                request_serializer=hivebox_dot_v1_dot_cells__pb2.WatchCellsRequest.SerializeToString,
                response_deserializer=hivebox_dot_v1_dot_cells__pb2.CellEvent.FromString,
                _registered_method=True)
        self.Pause = channel.unary_unary(
                '/hivebox.v1.Cells/Pause',
                request_serializer=hivebox_dot_v1_dot_types__pb2.CellSelector.SerializeToString,
                response_deserializer=hivebox_dot_v1_dot_types__pb2.BulkResult.FromString,
                _registered_method=True)
        self.Resume = channel.unary_unary(
                '/hivebox.v1.Cells/Resume',
                request_serializer=hivebox_dot_v1_dot_types__pb2.CellSelector.SerializeToString,
                response_deserializer=hivebox_dot_v1_dot_types__pb2.BulkResult.FromString,
                _registered_method=True)
        self.Stop = channel.unary_unary(
                '/hivebox.v1.Cells/Stop',
                request_serializer=hivebox_dot_v1_dot_cells__pb2.StopRequest.SerializeToString,
                response_deserializer=hivebox_dot_v1_dot_types__pb2.BulkResult.FromString,
                _registered_method=True)
        self.Quarantine = channel.unary_unary(
                '/hivebox.v1.Cells/Quarantine',
                request_serializer=hivebox_dot_v1_dot_cells__pb2.QuarantineRequest.SerializeToString,
                response_deserializer=hivebox_dot_v1_dot_cells__pb2.QuarantineResponse.FromString,
                _registered_method=True)
        self.ExtendTtl = channel.unary_unary(
                '/hivebox.v1.Cells/ExtendTtl',
                request_serializer=hivebox_dot_v1_dot_cells__pb2.ExtendTtlRequest.SerializeToString,
                response_deserializer=hivebox_dot_v1_dot_types__pb2.Cell.FromString,
                _registered_method=True)
        self.UpdatePolicy = channel.unary_unary(
                '/hivebox.v1.Cells/UpdatePolicy',
                request_serializer=hivebox_dot_v1_dot_cells__pb2.UpdatePolicyRequest.SerializeToString,
                response_deserializer=hivebox_dot_v1_dot_types__pb2.Cell.FromString,
                _registered_method=True)
        self.ExposePort = channel.unary_unary(
                '/hivebox.v1.Cells/ExposePort',
                request_serializer=hivebox_dot_v1_dot_cells__pb2.ExposePortRequest.SerializeToString,
                response_deserializer=hivebox_dot_v1_dot_cells__pb2.PortEndpoint.FromString,
                _registered_method=True)


class CellsServicer:
    """Missing associated documentation comment in .proto file."""

    def Create(self, request, context):
        """Creates count cells from one spec and streams one event per cell as each is ready or fails.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Watch(self, request, context):
        """Streams state transitions for the selected cells, starting with their current state.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Pause(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Resume(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Quarantine(self, request, context):
        """Freezes each cell for good, cuts it off the network and keeps an unscrubbed disk snapshot of
        it for forensics. A quarantined cell stays paused until it is stopped: it cannot be resumed
        and no timer stops it.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExtendTtl(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePolicy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExposePort(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CellsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_stream_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=hivebox_dot_v1_dot_cells__pb2.CreateRequest.FromString,
                    response_serializer=hivebox_dot_v1_dot_cells__pb2.CreateEvent.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=hivebox_dot_v1_dot_cells__pb2.GetCellRequest.FromString,
                    response_serializer=hivebox_dot_v1_dot_types__pb2.Cell.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=hivebox_dot_v1_dot_cells__pb2.ListCellsRequest.FromString,
                    response_serializer=hivebox_dot_v1_dot_cells__pb2.ListCellsResponse.SerializeToString,
            ),
            'Watch': grpc.unary_stream_rpc_method_handler(
                    servicer.Watch,
                    request_deserializer=hivebox_dot_v1_dot_cells__pb2.WatchCellsRequest.FromString,
                    response_serializer=hivebox_dot_v1_dot_cells__pb2.CellEvent.SerializeToString,
            ),
            'Pause': grpc.unary_unary_rpc_method_handler(
                    servicer.Pause,
                    request_deserializer=hivebox_dot_v1_dot_types__pb2.CellSelector.FromString,
                    response_serializer=hivebox_dot_v1_dot_types__pb2.BulkResult.SerializeToString,
            ),
            'Resume': grpc.unary_unary_rpc_method_handler(
                    servicer.Resume,
                    request_deserializer=hivebox_dot_v1_dot_types__pb2.CellSelector.FromString,
                    response_serializer=hivebox_dot_v1_dot_types__pb2.BulkResult.SerializeToString,
            ),
            'Stop': grpc.unary_unary_rpc_method_handler(
                    servicer.Stop,
                    request_deserializer=hivebox_dot_v1_dot_cells__pb2.StopRequest.FromString,
                    response_serializer=hivebox_dot_v1_dot_types__pb2.BulkResult.SerializeToString,
            ),
            'Quarantine': grpc.unary_unary_rpc_method_handler(
                    servicer.Quarantine,
                    request_deserializer=hivebox_dot_v1_dot_cells__pb2.QuarantineRequest.FromString,
                    response_serializer=hivebox_dot_v1_dot_cells__pb2.QuarantineResponse.SerializeToString,
            ),
            'ExtendTtl': grpc.unary_unary_rpc_method_handler(
                    servicer.ExtendTtl,
                    request_deserializer=hivebox_dot_v1_dot_cells__pb2.ExtendTtlRequest.FromString,
                    response_serializer=hivebox_dot_v1_dot_types__pb2.Cell.SerializeToString,
            ),
            'UpdatePolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePolicy,
                    request_deserializer=hivebox_dot_v1_dot_cells__pb2.UpdatePolicyRequest.FromString,
                    response_serializer=hivebox_dot_v1_dot_types__pb2.Cell.SerializeToString,
            ),
            'ExposePort': grpc.unary_unary_rpc_method_handler(
                    servicer.ExposePort,
                    request_deserializer=hivebox_dot_v1_dot_cells__pb2.ExposePortRequest.FromString,
                    response_serializer=hivebox_dot_v1_dot_cells__pb2.PortEndpoint.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hivebox.v1.Cells', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hivebox.v1.Cells', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Cells:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/hivebox.v1.Cells/Create',
            hivebox_dot_v1_dot_cells__pb2.CreateRequest.SerializeToString,
            hivebox_dot_v1_dot_cells__pb2.CreateEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hivebox.v1.Cells/Get',
            hivebox_dot_v1_dot_cells__pb2.GetCellRequest.SerializeToString,
            hivebox_dot_v1_dot_types__pb2.Cell.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hivebox.v1.Cells/List',
            hivebox_dot_v1_dot_cells__pb2.ListCellsRequest.SerializeToString,
            hivebox_dot_v1_dot_cells__pb2.ListCellsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Watch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/hivebox.v1.Cells/Watch',
            hivebox_dot_v1_dot_cells__pb2.WatchCellsRequest.SerializeToString,
            hivebox_dot_v1_dot_cells__pb2.CellEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Pause(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hivebox.v1.Cells/Pause',
            hivebox_dot_v1_dot_types__pb2.CellSelector.SerializeToString,
            hivebox_dot_v1_dot_types__pb2.BulkResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Resume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hivebox.v1.Cells/Resume',
            hivebox_dot_v1_dot_types__pb2.CellSelector.SerializeToString,
            hivebox_dot_v1_dot_types__pb2.BulkResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hivebox.v1.Cells/Stop',
            hivebox_dot_v1_dot_cells__pb2.StopRequest.SerializeToString,
            hivebox_dot_v1_dot_types__pb2.BulkResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Quarantine(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hivebox.v1.Cells/Quarantine',
            hivebox_dot_v1_dot_cells__pb2.QuarantineRequest.SerializeToString,
            hivebox_dot_v1_dot_cells__pb2.QuarantineResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExtendTtl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hivebox.v1.Cells/ExtendTtl',
            hivebox_dot_v1_dot_cells__pb2.ExtendTtlRequest.SerializeToString,
            hivebox_dot_v1_dot_types__pb2.Cell.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hivebox.v1.Cells/UpdatePolicy',
            hivebox_dot_v1_dot_cells__pb2.UpdatePolicyRequest.SerializeToString,
            hivebox_dot_v1_dot_types__pb2.Cell.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExposePort(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hivebox.v1.Cells/ExposePort',
            hivebox_dot_v1_dot_cells__pb2.ExposePortRequest.SerializeToString,
            hivebox_dot_v1_dot_cells__pb2.PortEndpoint.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
