# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from hivebox.v1 import exec_pb2 as hivebox_dot_v1_dot_exec__pb2
from hivebox.v1 import types_pb2 as hivebox_dot_v1_dot_types__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in hivebox/v1/exec_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ExecStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Run = channel.unary_unary(
                '/hivebox.v1.Exec/Run',
                request_serializer=hivebox_dot_v1_dot_exec__pb2.RunRequest.SerializeToString,
                response_deserializer=hivebox_dot_v1_dot_exec__pb2.RunResult.FromString,
                _registered_method=True)
        self.Start = channel.stream_stream(
                '/hivebox.v1.Exec/Start',
                request_serializer=hivebox_dot_v1_dot_exec__pb2.ProcessInput.SerializeToString,
                response_deserializer=hivebox_dot_v1_dot_exec__pb2.ProcessOutput.FromString,
                _registered_method=True)
        self.Signal = channel.unary_unary(
                '/hivebox.v1.Exec/Signal',
                request_serializer=hivebox_dot_v1_dot_exec__pb2.SignalRequest.SerializeToString,
                response_deserializer=hivebox_dot_v1_dot_types__pb2.Empty.FromString,
                _registered_method=True)
        self.SessionCreate = channel.unary_unary(
                '/hivebox.v1.Exec/SessionCreate',
                request_serializer=hivebox_dot_v1_dot_exec__pb2.SessionCreateRequest.SerializeToString,
                response_deserializer=hivebox_dot_v1_dot_exec__pb2.Session.FromString,
                _registered_method=True)
        self.SessionRun = channel.unary_unary(
                '/hivebox.v1.Exec/SessionRun',
                request_serializer=hivebox_dot_v1_dot_exec__pb2.SessionRunRequest.SerializeToString,
                response_deserializer=hivebox_dot_v1_dot_exec__pb2.SessionRunResult.FromString,
                _registered_method=True)
        self.SessionInteract = channel.stream_stream(
                '/hivebox.v1.Exec/SessionInteract',
                request_serializer=hivebox_dot_v1_dot_exec__pb2.SessionInput.SerializeToString,
                response_deserializer=hivebox_dot_v1_dot_exec__pb2.SessionOutput.FromString,
                _registered_method=True)
        self.SessionClose = channel.unary_unary(
                '/hivebox.v1.Exec/SessionClose',
                request_serializer=hivebox_dot_v1_dot_exec__pb2.SessionRef.SerializeToString,
                response_deserializer=hivebox_dot_v1_dot_types__pb2.Empty.FromString,
                _registered_method=True)


class ExecServicer:
    """Missing associated documentation comment in .proto file."""

    def Run(self, request, context):
        """Runs one command to completion and returns its output, capped at max_output_bytes.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Start(self, request_iterator, context):
        """Runs a command with streamed input and output. The first message must be a start.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Signal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SessionCreate(self, request, context):
        """Opens a persistent shell whose state (cwd, env, background jobs) carries over between runs.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SessionRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SessionInteract(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SessionClose(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExecServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Run': grpc.unary_unary_rpc_method_handler(
                    servicer.Run,
                    request_deserializer=hivebox_dot_v1_dot_exec__pb2.RunRequest.FromString,
                    response_serializer=hivebox_dot_v1_dot_exec__pb2.RunResult.SerializeToString,
            ),
            'Start': grpc.stream_stream_rpc_method_handler(
                    servicer.Start,
                    request_deserializer=hivebox_dot_v1_dot_exec__pb2.ProcessInput.FromString,
                    response_serializer=hivebox_dot_v1_dot_exec__pb2.ProcessOutput.SerializeToString,
            ),
            'Signal': grpc.unary_unary_rpc_method_handler(
                    servicer.Signal,
                    request_deserializer=hivebox_dot_v1_dot_exec__pb2.SignalRequest.FromString,
                    response_serializer=hivebox_dot_v1_dot_types__pb2.Empty.SerializeToString,
            ),
            'SessionCreate': grpc.unary_unary_rpc_method_handler(
                    servicer.SessionCreate,
                    request_deserializer=hivebox_dot_v1_dot_exec__pb2.SessionCreateRequest.FromString,
                    response_serializer=hivebox_dot_v1_dot_exec__pb2.Session.SerializeToString,
            ),
            'SessionRun': grpc.unary_unary_rpc_method_handler(
                    servicer.SessionRun,
                    request_deserializer=hivebox_dot_v1_dot_exec__pb2.SessionRunRequest.FromString,
                    response_serializer=hivebox_dot_v1_dot_exec__pb2.SessionRunResult.SerializeToString,
            ),
            'SessionInteract': grpc.stream_stream_rpc_method_handler(
                    servicer.SessionInteract,
                    request_deserializer=hivebox_dot_v1_dot_exec__pb2.SessionInput.FromString,
                    response_serializer=hivebox_dot_v1_dot_exec__pb2.SessionOutput.SerializeToString,
            ),
            'SessionClose': grpc.unary_unary_rpc_method_handler(
                    servicer.SessionClose,
                    request_deserializer=hivebox_dot_v1_dot_exec__pb2.SessionRef.FromString,
                    response_serializer=hivebox_dot_v1_dot_types__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hivebox.v1.Exec', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hivebox.v1.Exec', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Exec:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Run(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hivebox.v1.Exec/Run',
            hivebox_dot_v1_dot_exec__pb2.RunRequest.SerializeToString,
            hivebox_dot_v1_dot_exec__pb2.RunResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Start(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/hivebox.v1.Exec/Start',
            hivebox_dot_v1_dot_exec__pb2.ProcessInput.SerializeToString,
            hivebox_dot_v1_dot_exec__pb2.ProcessOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Signal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hivebox.v1.Exec/Signal',
            hivebox_dot_v1_dot_exec__pb2.SignalRequest.SerializeToString,
            hivebox_dot_v1_dot_types__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SessionCreate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hivebox.v1.Exec/SessionCreate',
            hivebox_dot_v1_dot_exec__pb2.SessionCreateRequest.SerializeToString,
            hivebox_dot_v1_dot_exec__pb2.Session.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SessionRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hivebox.v1.Exec/SessionRun',
            hivebox_dot_v1_dot_exec__pb2.SessionRunRequest.SerializeToString,
            hivebox_dot_v1_dot_exec__pb2.SessionRunResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SessionInteract(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/hivebox.v1.Exec/SessionInteract',
            hivebox_dot_v1_dot_exec__pb2.SessionInput.SerializeToString,
            hivebox_dot_v1_dot_exec__pb2.SessionOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SessionClose(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hivebox.v1.Exec/SessionClose',
            hivebox_dot_v1_dot_exec__pb2.SessionRef.SerializeToString,
            hivebox_dot_v1_dot_types__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
