# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from hivebox.v1 import files_pb2 as hivebox_dot_v1_dot_files__pb2
from hivebox.v1 import types_pb2 as hivebox_dot_v1_dot_types__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in hivebox/v1/files_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FilesStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Read = channel.unary_stream(
                '/hivebox.v1.Files/Read',
                request_serializer=hivebox_dot_v1_dot_files__pb2.ReadFileRequest.SerializeToString,
                response_deserializer=hivebox_dot_v1_dot_files__pb2.Chunk.FromString,
                _registered_method=True)
        self.Write = channel.stream_unary(
                '/hivebox.v1.Files/Write',
                request_serializer=hivebox_dot_v1_dot_files__pb2.WriteFileChunk.SerializeToString,
                response_deserializer=hivebox_dot_v1_dot_files__pb2.FileInfo.FromString,
                _registered_method=True)
        self.Stat = channel.unary_unary(
                '/hivebox.v1.Files/Stat',
                request_serializer=hivebox_dot_v1_dot_files__pb2.PathRequest.SerializeToString,
                response_deserializer=hivebox_dot_v1_dot_files__pb2.FileInfo.FromString,
                _registered_method=True)
        self.List = channel.unary_unary(
                '/hivebox.v1.Files/List',
                request_serializer=hivebox_dot_v1_dot_files__pb2.ListDirRequest.SerializeToString,
                response_deserializer=hivebox_dot_v1_dot_files__pb2.ListDirResponse.FromString,
                _registered_method=True)
        self.Remove = channel.unary_unary(
                '/hivebox.v1.Files/Remove',
                request_serializer=hivebox_dot_v1_dot_files__pb2.PathRequest.SerializeToString,
                response_deserializer=hivebox_dot_v1_dot_types__pb2.Empty.FromString,
                _registered_method=True)
        self.Watch = channel.unary_stream(
                '/hivebox.v1.Files/Watch',
                request_serializer=hivebox_dot_v1_dot_files__pb2.WatchDirRequest.SerializeToString,
                response_deserializer=hivebox_dot_v1_dot_files__pb2.FsEvent.FromString,
                _registered_method=True)
        self.Diff = channel.unary_unary(
                '/hivebox.v1.Files/Diff',
                request_serializer=hivebox_dot_v1_dot_files__pb2.DiffRequest.SerializeToString,
                response_deserializer=hivebox_dot_v1_dot_files__pb2.DiffResult.FromString,
                _registered_method=True)
        self.Apply = channel.unary_unary(
                '/hivebox.v1.Files/Apply',
                request_serializer=hivebox_dot_v1_dot_files__pb2.ApplyRequest.SerializeToString,
                response_deserializer=hivebox_dot_v1_dot_types__pb2.Empty.FromString,
                _registered_method=True)


class FilesServicer:
    """Missing associated documentation comment in .proto file."""

    def Read(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Write(self, request_iterator, context):
        """The first message must carry the header.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Remove(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Watch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Diff(self, request, context):
        """The changes since the cell started, as a git diff or as a layer diff.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Apply(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FilesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Read': grpc.unary_stream_rpc_method_handler(
                    servicer.Read,
                    request_deserializer=hivebox_dot_v1_dot_files__pb2.ReadFileRequest.FromString,
                    response_serializer=hivebox_dot_v1_dot_files__pb2.Chunk.SerializeToString,
            ),
            'Write': grpc.stream_unary_rpc_method_handler(
                    servicer.Write,
                    request_deserializer=hivebox_dot_v1_dot_files__pb2.WriteFileChunk.FromString,
                    response_serializer=hivebox_dot_v1_dot_files__pb2.FileInfo.SerializeToString,
            ),
            'Stat': grpc.unary_unary_rpc_method_handler(
                    servicer.Stat,
                    request_deserializer=hivebox_dot_v1_dot_files__pb2.PathRequest.FromString,
                    response_serializer=hivebox_dot_v1_dot_files__pb2.FileInfo.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=hivebox_dot_v1_dot_files__pb2.ListDirRequest.FromString,
                    response_serializer=hivebox_dot_v1_dot_files__pb2.ListDirResponse.SerializeToString,
            ),
            'Remove': grpc.unary_unary_rpc_method_handler(
                    servicer.Remove,
                    request_deserializer=hivebox_dot_v1_dot_files__pb2.PathRequest.FromString,
                    response_serializer=hivebox_dot_v1_dot_types__pb2.Empty.SerializeToString,
            ),
            'Watch': grpc.unary_stream_rpc_method_handler(
                    servicer.Watch,
                    request_deserializer=hivebox_dot_v1_dot_files__pb2.WatchDirRequest.FromString,
                    response_serializer=hivebox_dot_v1_dot_files__pb2.FsEvent.SerializeToString,
            ),
            'Diff': grpc.unary_unary_rpc_method_handler(
                    servicer.Diff,
                    request_deserializer=hivebox_dot_v1_dot_files__pb2.DiffRequest.FromString,
                    response_serializer=hivebox_dot_v1_dot_files__pb2.DiffResult.SerializeToString,
            ),
            'Apply': grpc.unary_unary_rpc_method_handler(
                    servicer.Apply,
                    request_deserializer=hivebox_dot_v1_dot_files__pb2.ApplyRequest.FromString,
                    response_serializer=hivebox_dot_v1_dot_types__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hivebox.v1.Files', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hivebox.v1.Files', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Files:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Read(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/hivebox.v1.Files/Read',
            hivebox_dot_v1_dot_files__pb2.ReadFileRequest.SerializeToString,
            hivebox_dot_v1_dot_files__pb2.Chunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Write(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/hivebox.v1.Files/Write',
            hivebox_dot_v1_dot_files__pb2.WriteFileChunk.SerializeToString,
            hivebox_dot_v1_dot_files__pb2.FileInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hivebox.v1.Files/Stat',
            hivebox_dot_v1_dot_files__pb2.PathRequest.SerializeToString,
            hivebox_dot_v1_dot_files__pb2.FileInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hivebox.v1.Files/List',
            hivebox_dot_v1_dot_files__pb2.ListDirRequest.SerializeToString,
            hivebox_dot_v1_dot_files__pb2.ListDirResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Remove(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hivebox.v1.Files/Remove',
            hivebox_dot_v1_dot_files__pb2.PathRequest.SerializeToString,
            hivebox_dot_v1_dot_types__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Watch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/hivebox.v1.Files/Watch',
            hivebox_dot_v1_dot_files__pb2.WatchDirRequest.SerializeToString,
            hivebox_dot_v1_dot_files__pb2.FsEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Diff(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hivebox.v1.Files/Diff',
            hivebox_dot_v1_dot_files__pb2.DiffRequest.SerializeToString,
            hivebox_dot_v1_dot_files__pb2.DiffResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Apply(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hivebox.v1.Files/Apply',
            hivebox_dot_v1_dot_files__pb2.ApplyRequest.SerializeToString,
            hivebox_dot_v1_dot_types__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
