# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hivebox/v1/images.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'hivebox/v1/images.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from hivebox.v1 import types_pb2 as hivebox_dot_v1_dot_types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17hivebox/v1/images.proto\x12\nhivebox.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x16hivebox/v1/types.proto\"_\n\rImportRequest\x12\x11\n\x07oci_ref\x18\x01 \x01(\tH\x00\x12\r\n\x03tar\x18\x02 \x01(\x0cH\x00\x12\x14\n\ndockerfile\x18\x03 \x01(\tH\x00\x12\x0c\n\x04name\x18\x04 \x01(\tB\x08\n\x06source\"s\n\nBuildEvent\x12\r\n\x03log\x18\x01 \x01(\tH\x00\x12)\n\x04\x64one\x18\x02 \x01(\x0b\x32\x19.hivebox.v1.ImageManifestH\x00\x12\"\n\x05\x65rror\x18\x03 \x01(\x0b\x32\x11.hivebox.v1.ErrorH\x00\x42\x07\n\x05\x65vent\"\x96\x01\n\rImageManifest\x12!\n\x03ref\x18\x01 \x01(\x0b\x32\x14.hivebox.v1.ImageRef\x12\x0e\n\x06\x64igest\x18\x02 \x01(\t\x12\x12\n\nsize_bytes\x18\x03 \x01(\x04\x12\x0e\n\x06layers\x18\x04 \x03(\t\x12.\n\ncreated_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"j\n\x0e\x43omposeRequest\x12\"\n\x04\x62\x61se\x18\x01 \x01(\x0b\x32\x14.hivebox.v1.ImageRef\x12&\n\x08overlays\x18\x02 \x03(\x0b\x32\x14.hivebox.v1.ImageRef\x12\x0c\n\x04name\x18\x03 \x01(\t\"F\n\x0fPrefetchRequest\x12$\n\x06images\x18\x01 \x03(\x0b\x32\x14.hivebox.v1.ImageRef\x12\r\n\x05nodes\x18\x02 \x01(\r2\xf8\x01\n\x06Images\x12=\n\x06Import\x12\x19.hivebox.v1.ImportRequest\x1a\x16.hivebox.v1.BuildEvent0\x01\x12\x36\n\x03Get\x12\x14.hivebox.v1.ImageRef\x1a\x19.hivebox.v1.ImageManifest\x12;\n\x07\x43ompose\x12\x1a.hivebox.v1.ComposeRequest\x1a\x14.hivebox.v1.ImageRef\x12:\n\x08Prefetch\x12\x1b.hivebox.v1.PrefetchRequest\x1a\x11.hivebox.v1.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hivebox.v1.images_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMPORTREQUEST']._serialized_start=96
  _globals['_IMPORTREQUEST']._serialized_end=191
  _globals['_BUILDEVENT']._serialized_start=193
  _globals['_BUILDEVENT']._serialized_end=308
  _globals['_IMAGEMANIFEST']._serialized_start=311
  _globals['_IMAGEMANIFEST']._serialized_end=461
  _globals['_COMPOSEREQUEST']._serialized_start=463
  _globals['_COMPOSEREQUEST']._serialized_end=569
  _globals['_PREFETCHREQUEST']._serialized_start=571
  _globals['_PREFETCHREQUEST']._serialized_end=641
  _globals['_IMAGES']._serialized_start=644
  _globals['_IMAGES']._serialized_end=892
# @@protoc_insertion_point(module_scope)
