# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from hivebox.v1 import images_pb2 as hivebox_dot_v1_dot_images__pb2
from hivebox.v1 import types_pb2 as hivebox_dot_v1_dot_types__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in hivebox/v1/images_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ImagesStub:
    """Draft: Import from an OCI reference lands in M0. The other sources and Compose come later.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Import = channel.unary_stream(
                '/hivebox.v1.Images/Import',
                request_serializer=hivebox_dot_v1_dot_images__pb2.ImportRequest.SerializeToString,
                response_deserializer=hivebox_dot_v1_dot_images__pb2.BuildEvent.FromString,
                _registered_method=True)
        self.Get = channel.unary_unary(
                '/hivebox.v1.Images/Get',
                request_serializer=hivebox_dot_v1_dot_types__pb2.ImageRef.SerializeToString,
                response_deserializer=hivebox_dot_v1_dot_images__pb2.ImageManifest.FromString,
                _registered_method=True)
        self.Compose = channel.unary_unary(
                '/hivebox.v1.Images/Compose',
                request_serializer=hivebox_dot_v1_dot_images__pb2.ComposeRequest.SerializeToString,
                response_deserializer=hivebox_dot_v1_dot_types__pb2.ImageRef.FromString,
                _registered_method=True)
        self.Prefetch = channel.unary_unary(
                '/hivebox.v1.Images/Prefetch',
                request_serializer=hivebox_dot_v1_dot_images__pb2.PrefetchRequest.SerializeToString,
                response_deserializer=hivebox_dot_v1_dot_types__pb2.Empty.FromString,
                _registered_method=True)


class ImagesServicer:
    """Draft: Import from an OCI reference lands in M0. The other sources and Compose come later.
    """

    def Import(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Compose(self, request, context):
        """Stacks a base image, a workspace and toolkits into one image without a build.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Prefetch(self, request, context):
        """Pulls an image onto nodes ahead of a burst.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImagesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Import': grpc.unary_stream_rpc_method_handler(
                    servicer.Import,
                    request_deserializer=hivebox_dot_v1_dot_images__pb2.ImportRequest.FromString,
                    response_serializer=hivebox_dot_v1_dot_images__pb2.BuildEvent.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=hivebox_dot_v1_dot_types__pb2.ImageRef.FromString,
                    response_serializer=hivebox_dot_v1_dot_images__pb2.ImageManifest.SerializeToString,
            ),
            'Compose': grpc.unary_unary_rpc_method_handler(
                    servicer.Compose,
                    request_deserializer=hivebox_dot_v1_dot_images__pb2.ComposeRequest.FromString,
                    response_serializer=hivebox_dot_v1_dot_types__pb2.ImageRef.SerializeToString,
            ),
            'Prefetch': grpc.unary_unary_rpc_method_handler(
                    servicer.Prefetch,
                    request_deserializer=hivebox_dot_v1_dot_images__pb2.PrefetchRequest.FromString,
                    response_serializer=hivebox_dot_v1_dot_types__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hivebox.v1.Images', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hivebox.v1.Images', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Images:
    """Draft: Import from an OCI reference lands in M0. The other sources and Compose come later.
    """

    @staticmethod
    def Import(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/hivebox.v1.Images/Import',
            hivebox_dot_v1_dot_images__pb2.ImportRequest.SerializeToString,
            hivebox_dot_v1_dot_images__pb2.BuildEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hivebox.v1.Images/Get',
            hivebox_dot_v1_dot_types__pb2.ImageRef.SerializeToString,
            hivebox_dot_v1_dot_images__pb2.ImageManifest.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Compose(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hivebox.v1.Images/Compose',
            hivebox_dot_v1_dot_images__pb2.ComposeRequest.SerializeToString,
            hivebox_dot_v1_dot_types__pb2.ImageRef.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Prefetch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hivebox.v1.Images/Prefetch',
            hivebox_dot_v1_dot_images__pb2.PrefetchRequest.SerializeToString,
            hivebox_dot_v1_dot_types__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
