# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from hivebox.v1 import llm_pb2 as hivebox_dot_v1_dot_llm__pb2
from hivebox.v1 import types_pb2 as hivebox_dot_v1_dot_types__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in hivebox/v1/llm_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LlmStub:
    """The LLM gateway each node runs for cells with the `llm` network profile, which reach it at
    http://llm.hive.internal. It forwards OpenAI and Anthropic style calls to the project's
    inference engine with the engine's key, which the cell never sees, and keeps the token ids of
    each call for the trainer.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetRoute = channel.unary_unary(
                '/hivebox.v1.Llm/SetRoute',
                request_serializer=hivebox_dot_v1_dot_llm__pb2.LlmRoute.SerializeToString,
                response_deserializer=hivebox_dot_v1_dot_types__pb2.Empty.FromString,
                _registered_method=True)
        self.Hold = channel.unary_unary(
                '/hivebox.v1.Llm/Hold',
                request_serializer=hivebox_dot_v1_dot_llm__pb2.LlmHoldRequest.SerializeToString,
                response_deserializer=hivebox_dot_v1_dot_llm__pb2.LlmHoldResult.FromString,
                _registered_method=True)
        self.Turns = channel.unary_unary(
                '/hivebox.v1.Llm/Turns',
                request_serializer=hivebox_dot_v1_dot_llm__pb2.LlmTurnsRequest.SerializeToString,
                response_deserializer=hivebox_dot_v1_dot_llm__pb2.LlmTurnsResponse.FromString,
                _registered_method=True)


class LlmServicer:
    """The LLM gateway each node runs for cells with the `llm` network profile, which reach it at
    http://llm.hive.internal. It forwards OpenAI and Anthropic style calls to the project's
    inference engine with the engine's key, which the cell never sees, and keeps the token ids of
    each call for the trainer.
    """

    def SetRoute(self, request, context):
        """Sets where calls from the project's cells go on this node.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Hold(self, request, context):
        """Answers new calls from the project's cells with 503 and Retry-After, as while the engine
        loads new weights, and waits for the calls in flight to end.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Turns(self, request, context):
        """The calls the project's cells made, with their token ids.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LlmServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetRoute': grpc.unary_unary_rpc_method_handler(
                    servicer.SetRoute,
                    request_deserializer=hivebox_dot_v1_dot_llm__pb2.LlmRoute.FromString,
                    response_serializer=hivebox_dot_v1_dot_types__pb2.Empty.SerializeToString,
            ),
            'Hold': grpc.unary_unary_rpc_method_handler(
                    servicer.Hold,
                    request_deserializer=hivebox_dot_v1_dot_llm__pb2.LlmHoldRequest.FromString,
                    response_serializer=hivebox_dot_v1_dot_llm__pb2.LlmHoldResult.SerializeToString,
            ),
            'Turns': grpc.unary_unary_rpc_method_handler(
                    servicer.Turns,
                    request_deserializer=hivebox_dot_v1_dot_llm__pb2.LlmTurnsRequest.FromString,
                    response_serializer=hivebox_dot_v1_dot_llm__pb2.LlmTurnsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hivebox.v1.Llm', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hivebox.v1.Llm', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Llm:
    """The LLM gateway each node runs for cells with the `llm` network profile, which reach it at
    http://llm.hive.internal. It forwards OpenAI and Anthropic style calls to the project's
    inference engine with the engine's key, which the cell never sees, and keeps the token ids of
    each call for the trainer.
    """

    @staticmethod
    def SetRoute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hivebox.v1.Llm/SetRoute',
            hivebox_dot_v1_dot_llm__pb2.LlmRoute.SerializeToString,
            hivebox_dot_v1_dot_types__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Hold(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hivebox.v1.Llm/Hold',
            hivebox_dot_v1_dot_llm__pb2.LlmHoldRequest.SerializeToString,
            hivebox_dot_v1_dot_llm__pb2.LlmHoldResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Turns(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hivebox.v1.Llm/Turns',
            hivebox_dot_v1_dot_llm__pb2.LlmTurnsRequest.SerializeToString,
            hivebox_dot_v1_dot_llm__pb2.LlmTurnsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
