# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hivebox/v1/snapshots.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'hivebox/v1/snapshots.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from hivebox.v1 import cells_pb2 as hivebox_dot_v1_dot_cells__pb2
from hivebox.v1 import types_pb2 as hivebox_dot_v1_dot_types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1ahivebox/v1/snapshots.proto\x12\nhivebox.v1\x1a\x16hivebox/v1/cells.proto\x1a\x16hivebox/v1/types.proto\"\xe4\x01\n\x0fSnapshotRequest\x12\x0f\n\x07\x63\x65ll_id\x18\x01 \x01(\t\x12&\n\x04kind\x18\x02 \x01(\x0e\x32\x18.hivebox.v1.SnapshotKind\x12\x37\n\x06labels\x18\x03 \x03(\x0b\x32\'.hivebox.v1.SnapshotRequest.LabelsEntry\x12\r\n\x05scrub\x18\x04 \x01(\x08\x12\r\n\x05\x61llow\x18\x05 \x03(\t\x12\x12\n\nsquash_git\x18\x06 \x03(\t\x1a-\n\x0bLabelsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x87\x01\n\x0eRestoreRequest\x12)\n\x08snapshot\x18\x01 \x01(\x0b\x32\x17.hivebox.v1.SnapshotRef\x12\r\n\x05\x63ount\x18\x02 \x01(\r\x12\"\n\x04spec\x18\x03 \x01(\x0b\x32\x14.hivebox.v1.CellSpec\x12\x17\n\x0fidempotency_key\x18\x04 \x01(\t\"\xaa\x01\n\x0b\x46orkRequest\x12\x0f\n\x07\x63\x65ll_id\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\r\x12\x33\n\x06labels\x18\x03 \x03(\x0b\x32#.hivebox.v1.ForkRequest.LabelsEntry\x12\x17\n\x0fidempotency_key\x18\x04 \x01(\t\x1a-\n\x0bLabelsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"H\n\rCommitRequest\x12)\n\x08snapshot\x18\x01 \x01(\x0b\x32\x17.hivebox.v1.SnapshotRef\x12\x0c\n\x04name\x18\x02 \x01(\t*y\n\x0cSnapshotKind\x12\x1d\n\x19SNAPSHOT_KIND_UNSPECIFIED\x10\x00\x12\x16\n\x12SNAPSHOT_KIND_DISK\x10\x01\x12\x1a\n\x16SNAPSHOT_KIND_DISK_MEM\x10\x02\x12\x16\n\x12SNAPSHOT_KIND_PROC\x10\x03\x32\xbc\x02\n\tSnapshots\x12@\n\x08Snapshot\x12\x1b.hivebox.v1.SnapshotRequest\x1a\x17.hivebox.v1.SnapshotRef\x12@\n\x07Restore\x12\x1a.hivebox.v1.RestoreRequest\x1a\x17.hivebox.v1.CreateEvent0\x01\x12:\n\x04\x46ork\x12\x17.hivebox.v1.ForkRequest\x1a\x17.hivebox.v1.CreateEvent0\x01\x12\x39\n\x06\x43ommit\x12\x19.hivebox.v1.CommitRequest\x1a\x14.hivebox.v1.ImageRef\x12\x34\n\x06\x44\x65lete\x12\x17.hivebox.v1.SnapshotRef\x1a\x11.hivebox.v1.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hivebox.v1.snapshots_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SNAPSHOTREQUEST_LABELSENTRY']._loaded_options = None
  _globals['_SNAPSHOTREQUEST_LABELSENTRY']._serialized_options = b'8\001'
  _globals['_FORKREQUEST_LABELSENTRY']._loaded_options = None
  _globals['_FORKREQUEST_LABELSENTRY']._serialized_options = b'8\001'
  _globals['_SNAPSHOTKIND']._serialized_start=706
  _globals['_SNAPSHOTKIND']._serialized_end=827
  _globals['_SNAPSHOTREQUEST']._serialized_start=91
  _globals['_SNAPSHOTREQUEST']._serialized_end=319
  _globals['_SNAPSHOTREQUEST_LABELSENTRY']._serialized_start=274
  _globals['_SNAPSHOTREQUEST_LABELSENTRY']._serialized_end=319
  _globals['_RESTOREREQUEST']._serialized_start=322
  _globals['_RESTOREREQUEST']._serialized_end=457
  _globals['_FORKREQUEST']._serialized_start=460
  _globals['_FORKREQUEST']._serialized_end=630
  _globals['_FORKREQUEST_LABELSENTRY']._serialized_start=274
  _globals['_FORKREQUEST_LABELSENTRY']._serialized_end=319
  _globals['_COMMITREQUEST']._serialized_start=632
  _globals['_COMMITREQUEST']._serialized_end=704
  _globals['_SNAPSHOTS']._serialized_start=830
  _globals['_SNAPSHOTS']._serialized_end=1146
# @@protoc_insertion_point(module_scope)
