# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from hivebox.v1 import cells_pb2 as hivebox_dot_v1_dot_cells__pb2
from hivebox.v1 import snapshots_pb2 as hivebox_dot_v1_dot_snapshots__pb2
from hivebox.v1 import types_pb2 as hivebox_dot_v1_dot_types__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in hivebox/v1/snapshots_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SnapshotsStub:
    """Disk snapshots of container cells. A snapshot is an image in the node's image store, the cell's
    image plus one layer with what the cell wrote, and its id is the image's id, so any node on the
    same store can start cells from it. Fork, Delete and the other kinds are not in yet.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Snapshot = channel.unary_unary(
                '/hivebox.v1.Snapshots/Snapshot',
                request_serializer=hivebox_dot_v1_dot_snapshots__pb2.SnapshotRequest.SerializeToString,
                response_deserializer=hivebox_dot_v1_dot_types__pb2.SnapshotRef.FromString,
                _registered_method=True)
        self.Restore = channel.unary_stream(
                '/hivebox.v1.Snapshots/Restore',
                request_serializer=hivebox_dot_v1_dot_snapshots__pb2.RestoreRequest.SerializeToString,
                response_deserializer=hivebox_dot_v1_dot_cells__pb2.CreateEvent.FromString,
                _registered_method=True)
        self.Fork = channel.unary_stream(
                '/hivebox.v1.Snapshots/Fork',
                request_serializer=hivebox_dot_v1_dot_snapshots__pb2.ForkRequest.SerializeToString,
                response_deserializer=hivebox_dot_v1_dot_cells__pb2.CreateEvent.FromString,
                _registered_method=True)
        self.Commit = channel.unary_unary(
                '/hivebox.v1.Snapshots/Commit',
                request_serializer=hivebox_dot_v1_dot_snapshots__pb2.CommitRequest.SerializeToString,
                response_deserializer=hivebox_dot_v1_dot_types__pb2.ImageRef.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/hivebox.v1.Snapshots/Delete',
                request_serializer=hivebox_dot_v1_dot_types__pb2.SnapshotRef.SerializeToString,
                response_deserializer=hivebox_dot_v1_dot_types__pb2.Empty.FromString,
                _registered_method=True)


class SnapshotsServicer:
    """Disk snapshots of container cells. A snapshot is an image in the node's image store, the cell's
    image plus one layer with what the cell wrote, and its id is the image's id, so any node on the
    same store can start cells from it. Fork, Delete and the other kinds are not in yet.
    """

    def Snapshot(self, request, context):
        """Freezes the cell while its writes are read, and thaws it after if it was running.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Restore(self, request, context):
        """Starts count cells from one snapshot, the same as Cells.Create with the snapshot as source.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Fork(self, request, context):
        """Copies a running cell count times, at most 16.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Commit(self, request, context):
        """Names a scrubbed snapshot, so the project's cells can use the name as their image.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SnapshotsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Snapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.Snapshot,
                    request_deserializer=hivebox_dot_v1_dot_snapshots__pb2.SnapshotRequest.FromString,
                    response_serializer=hivebox_dot_v1_dot_types__pb2.SnapshotRef.SerializeToString,
            ),
            'Restore': grpc.unary_stream_rpc_method_handler(
                    servicer.Restore,
                    request_deserializer=hivebox_dot_v1_dot_snapshots__pb2.RestoreRequest.FromString,
                    response_serializer=hivebox_dot_v1_dot_cells__pb2.CreateEvent.SerializeToString,
            ),
            'Fork': grpc.unary_stream_rpc_method_handler(
                    servicer.Fork,
                    request_deserializer=hivebox_dot_v1_dot_snapshots__pb2.ForkRequest.FromString,
                    response_serializer=hivebox_dot_v1_dot_cells__pb2.CreateEvent.SerializeToString,
            ),
            'Commit': grpc.unary_unary_rpc_method_handler(
                    servicer.Commit,
                    request_deserializer=hivebox_dot_v1_dot_snapshots__pb2.CommitRequest.FromString,
                    response_serializer=hivebox_dot_v1_dot_types__pb2.ImageRef.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=hivebox_dot_v1_dot_types__pb2.SnapshotRef.FromString,
                    response_serializer=hivebox_dot_v1_dot_types__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hivebox.v1.Snapshots', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hivebox.v1.Snapshots', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Snapshots:
    """Disk snapshots of container cells. A snapshot is an image in the node's image store, the cell's
    image plus one layer with what the cell wrote, and its id is the image's id, so any node on the
    same store can start cells from it. Fork, Delete and the other kinds are not in yet.
    """

    @staticmethod
    def Snapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hivebox.v1.Snapshots/Snapshot',
            hivebox_dot_v1_dot_snapshots__pb2.SnapshotRequest.SerializeToString,
            hivebox_dot_v1_dot_types__pb2.SnapshotRef.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Restore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/hivebox.v1.Snapshots/Restore',
            hivebox_dot_v1_dot_snapshots__pb2.RestoreRequest.SerializeToString,
            hivebox_dot_v1_dot_cells__pb2.CreateEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Fork(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/hivebox.v1.Snapshots/Fork',
            hivebox_dot_v1_dot_snapshots__pb2.ForkRequest.SerializeToString,
            hivebox_dot_v1_dot_cells__pb2.CreateEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Commit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hivebox.v1.Snapshots/Commit',
            hivebox_dot_v1_dot_snapshots__pb2.CommitRequest.SerializeToString,
            hivebox_dot_v1_dot_types__pb2.ImageRef.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hivebox.v1.Snapshots/Delete',
            hivebox_dot_v1_dot_types__pb2.SnapshotRef.SerializeToString,
            hivebox_dot_v1_dot_types__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
