# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hivebox/v1/tokens.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'hivebox/v1/tokens.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17hivebox/v1/tokens.proto\x12\nhivebox.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"Y\n\x10MintTokenRequest\x12&\n\x03ttl\x18\x01 \x01(\x0b\x32\x19.google.protobuf.Duration\x12\x10\n\x08\x63\x65ll_ids\x18\x02 \x03(\t\x12\x0b\n\x03ops\x18\x03 \x03(\t\"F\n\x05Token\x12\r\n\x05token\x18\x01 \x01(\t\x12.\n\nexpires_at\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp2A\n\x06Tokens\x12\x37\n\x04Mint\x12\x1c.hivebox.v1.MintTokenRequest\x1a\x11.hivebox.v1.Tokenb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hivebox.v1.tokens_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MINTTOKENREQUEST']._serialized_start=104
  _globals['_MINTTOKENREQUEST']._serialized_end=193
  _globals['_TOKEN']._serialized_start=195
  _globals['_TOKEN']._serialized_end=265
  _globals['_TOKENS']._serialized_start=267
  _globals['_TOKENS']._serialized_end=332
# @@protoc_insertion_point(module_scope)
