# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from hivebox.v1 import tokens_pb2 as hivebox_dot_v1_dot_tokens__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in hivebox/v1/tokens_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TokensStub:
    """Tokens are biscuits signed by the keeper. A token opens the same project as the API key it was
    made with, for at most an hour, and its holder can narrow it down further without asking
    anyone, to some cells, some calls or a sooner end. Give a token, not the key, to code that
    should only reach part of a project, like an agent working in one cell.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Mint = channel.unary_unary(
                '/hivebox.v1.Tokens/Mint',
                request_serializer=hivebox_dot_v1_dot_tokens__pb2.MintTokenRequest.SerializeToString,
                response_deserializer=hivebox_dot_v1_dot_tokens__pb2.Token.FromString,
                _registered_method=True)


class TokensServicer:
    """Tokens are biscuits signed by the keeper. A token opens the same project as the API key it was
    made with, for at most an hour, and its holder can narrow it down further without asking
    anyone, to some cells, some calls or a sooner end. Give a token, not the key, to code that
    should only reach part of a project, like an agent working in one cell.
    """

    def Mint(self, request, context):
        """Makes a token from the API key the call carries. A token can not make another token.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TokensServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Mint': grpc.unary_unary_rpc_method_handler(
                    servicer.Mint,
                    request_deserializer=hivebox_dot_v1_dot_tokens__pb2.MintTokenRequest.FromString,
                    response_serializer=hivebox_dot_v1_dot_tokens__pb2.Token.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hivebox.v1.Tokens', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hivebox.v1.Tokens', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Tokens:
    """Tokens are biscuits signed by the keeper. A token opens the same project as the API key it was
    made with, for at most an hour, and its holder can narrow it down further without asking
    anyone, to some cells, some calls or a sooner end. Give a token, not the key, to code that
    should only reach part of a project, like an agent working in one cell.
    """

    @staticmethod
    def Mint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hivebox.v1.Tokens/Mint',
            hivebox_dot_v1_dot_tokens__pb2.MintTokenRequest.SerializeToString,
            hivebox_dot_v1_dot_tokens__pb2.Token.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
