[package]
name = "hive-sdk"
description = "The Rust client SDK for hivebox."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true
readme.workspace = true
publish.workspace = true

[dependencies]
bytes.workspace = true
futures.workspace = true
hive-proto.workspace = true
hive-types.workspace = true
hyper-util = { workspace = true, features = ["tokio"] }
tokio = { workspace = true, features = ["net", "sync"] }
tonic = { workspace = true, features = ["channel"] }
tower = { workspace = true, features = ["util"] }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }

[lints]
workspace = true
